# Generated by Django 5.2.16 on 2026-08-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='story_summary',
            field=models.TextField(blank=True),
        ),
    ]
