# Generated by Django 5.2.16 on 2026-08-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='questchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_challenges', to='quests.challenge'),
        ),
        migrations.AlterField(
            model_name='questchallenge',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_challenges', to='quests.quest'),
        ),
    ]
